version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r app/requirements.txt
  build:
    commands:
      - python -m py_compile app/app.py
      - echo "Build $CODEBUILD_BUILD_NUMBER passed checks"

artifacts:
  files:
    - appspec.yml
    - app/**/*
    - scripts/**/*
